version: '3.9'
services:
  mysql-debug:
    image: mysql:8
    container_name: nestjs
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sd
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: Europe/Bucharest
    ports:
      - 3306:3306
    volumes:
      - nestjs:/var/lib/mysql_stocks_wiki
    profiles:
      - debug
    networks:
      - nestjs-network
  api:
    container_name: "hrm_api_${NODE_ENV}"
    image: "hrm_api_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: ./
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
volumes:
  nestjs:
networks:
  nestjs-network: 
