version: '3.9'
services:
  envoy:
    container_name: 'envoy'
    build: ./envoy
    ports:
      - 8080:8080
    volumes:
      - ./envoy/envoy.yaml:/config/envoy.yaml
    networks:
      - nestjs-network
    depends_on:
      - api
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./:/app/project/data/:/var/lib/rabbitmq
      - ./:/app/project/log/:/var/log/rabbitmq
    networks:
      - nestjs-network
  mysql-debug:
    image: mysql:8
    container_name: db
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=sd
      # TZ: Europe/Bucharest
    ports:
      - 3306:3306
    # volumes:
    #   - nestjs:/var/lib/mysql_stocks_wiki
    # profiles:
    #   - debug
    networks:
      - nestjs-network
  api:
    container_name: "hrm_api_${NODE_ENV}"
    image: "hrm_api_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
    # build:
    #   context: ./
    #   target: "${NODE_ENV}"
    #   dockerfile: Dockerfile
    entrypoint: [ "npm", "run", "start:${NODE_ENV}" ]
    env_file:
      - .env
    ports:
      - 3000:3000
      - 5000:5000
    networks:
      - nestjs-network
    volumes:
      - ./:/app/project
    depends_on:
      - mysql-debug
    restart: unless-stopped
volumes:
  nestjs:
networks:
  nestjs-network:
